### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ChhR00** [fdx-xdf/darkPulse#1]
使用 -f 64 可以编译成功，但是生成的.EXE程序无法执行，报错，，改用 -f 32进行编译，提示编译失败：exit status 1 
这是什么原因呀，要怎么处理？

**Comment by fdx-xdf** [comment]
放不方便告诉我你的系统环境呀，以及使用的所有参数

**Comment by fdx-xdf** [comment]
64位下生成的exe报的什么错
