### ISSUE TITLE
关于编译的几个问题

### ISSUE THREAD

**Issue by yj94** [fdx-xdf/darkPulse#10]
使用模板编译我看你的参数有-lrpcrt4 -masm=intel 如何自己在VS里面编译program.c模板文件？
另外program.c的换行符规范是LF，建议改成windows适配的CRLF，因为visualstudio会报错！
我用VS想自行编译时出现问题，使用选项 #pragma comment(lib, "rpcrt4.lib") 无果，是不是要开启masm？但是VS里面没有asm文件无法开启
![image](https://github.com/fdx-xdf/darkPulse/assets/29896518/ec8a21cc-4f22-4b25-b2fc-5260f2faea75)
我希望能够自行添加自己想要的功能 且能够使用VS成功编译 望回复！谢谢

**Comment by fdx-xdf** [comment]
我是用的clion写的代码，并没有使用vs，关于编译参数的问题vs好像引入一个头文件就可以了，具体的文件名我忘了😂😂
另外gcc支持x64和x32都支持内敛汇编，所以汇编我就直接写到sys-32.c和sys-64.c里面了，并且gcc和msvc的汇编语法不太一样，所以不太好搞，如果一定要用vs的话可以去看看s3那个项目再重新生成一份文件

**Comment by yj94** [comment]
我就是因为SysWhispers3项目难跑的起来所以才想摘抄你项目里面syscall的代码。那我去用下clion编译下试试看。难受了XD

**Comment by fdx-xdf** [comment]
ok，还有问题的话留言就行

**Comment by yj94** [comment]
能不能给个联系方式呀 发我主页邮箱 ，我找不到你其他联系方式，不然这个issue的邮件提醒可要烦死你了 XD

**Comment by fdx-xdf** [comment]
你看我项目最下面写了，免责声明那
