### ISSUE TITLE
Rust编译失败

### ISSUE THREAD

**Issue by zwz12138** [fdx-xdf/darkPulse#13]
![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/8694d615-121c-4822-a610-79f6871991ca)
![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/fc7629f1-2313-49c6-99a5-99f91df2970b)

**Comment by zwz12138** [comment]
用的是stable-x86_64-pc-windows-gnu (default)
`>rustup toolchain list

stable-x86_64-pc-windows-gnu (default)`

**Comment by fdx-xdf** [comment]
在msys2里面运行下面命令了吗
$ pacman -Sy && pacman -Syu
$ pacman -S mingw-w64-x86_64-toolchain
如果还是不行，把rust从stable换成nightly版本试试

**Comment by zwz12138** [comment]
> 在msys2里面运行下面命令了吗 $ pacman -Sy && pacman -Syu $ pacman -S mingw-w64-x86_64-toolchain 如果还是不行，把rust从stable换成nightly版本试试

运行了，我换了试试吧

**Comment by zwz12138** [comment]
> 在msys2里面运行下面命令了吗 $ pacman -Sy && pacman -Syu $ pacman -S mingw-w64-x86_64-toolchain 如果还是不行，把rust从stable换成nightly版本试试

换了nightly，好像还是不行
![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/4b905c09-59d2-4e9a-9150-5d9dbe759390)

**Comment by fdx-xdf** [comment]
那如果进入rust_template目录下手动编译呢，先cargo clean，在cargo build --release

**Comment by zwz12138** [comment]
> 那如果进入rust_template目录下手动编译呢，先cargo clean，在cargo build --release

测试了，报错一样

![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/687a48c0-06a9-4e96-a229-d06f8a6eb74a)

**Comment by fdx-xdf** [comment]
你link的gcc是32位的，应该是config文件写错了

**Comment by zwz12138** [comment]
> 你link的gcc是32位的，应该是config文件写错了
config文件是根据师傅这边发的这个知乎帖子写的
[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\mingw64\\bin\\gcc.exe"
ar = "C:\\msys64\\mingw64\\bin\\ar.exe"

**Comment by fdx-xdf** [comment]
![Screenshot_20240607_145624](https://github.com/fdx-xdf/darkPulse/assets/117912115/87316611-cf6f-4860-a4d4-72a13e867e39)
![Screenshot_20240607_145611](https://github.com/fdx-xdf/darkPulse/assets/117912115/ce1e4198-f037-48c1-8b3a-c3ea3f0b7a81)
我看你第一次发的截图和后面发的截图的link的gcc不太一样，你看看现在rust default的工具链是哪个

**Comment by zwz12138** [comment]
> 你link的gcc是32位的，应该是config文件写错了



> ![Screenshot_20240607_145624](https://private-user-images.githubusercontent.com/117912115/337558034-87316611-cf6f-4860-a4d4-72a13e867e39.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDM4NjIsIm5iZiI6MTcxNzc0MzU2MiwicGF0aCI6Ii8xMTc5MTIxMTUvMzM3NTU4MDM0LTg3MzE2NjExLWNmNmYtNDg2MC1hNGQ0LTcyYTEzZTg2N2UzOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwNjU5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTFlZTI3ODExNzI2NWU1MTE5MTk1YTRiOWFmN2IwMGE5MzQ5NDJmYWViMjg4M2Y4MDY4YzI1NzY2OWZlOTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NjP3sKvB-fDeFTZsNRaEhLLsxODx8lDJn0iir7hU3R8) ![Screenshot_20240607_145611](https://private-user-images.githubusercontent.com/117912115/337558078-ce1e4198-f037-48c1-8b3a-c3ea3f0b7a81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDM4NjIsIm5iZiI6MTcxNzc0MzU2MiwicGF0aCI6Ii8xMTc5MTIxMTUvMzM3NTU4MDc4LWNlMWU0MTk4LWYwMzctNDhjMS04YjNhLWMzZWEzZjBiN2E4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwNjU5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWI4OTdmYzVkNzBhYTg4ZWY0YjNkNjEzOTE1OTQ5MTNjZWM2NWYyNzE1M2Y4YjBjODY1MjQ5MjE0MWVlYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q1Cg8X5SlpyiZPPSn2qjO94e-fSyoBiv_Rq4kAt5cio) 我看你第一次发的截图和后面发的截图的link的gcc不太一样，你看看现在rust default的工具链是哪个

![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/3994fc3d-e560-4eae-8ff8-7d91da892bec)
然后现在好像是出另一个问题了，编译提示缺少libgcc_s_seh-1.dll，然后我把dll放system目录后就调不了了
![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/c5c5bfd9-5c84-49e8-9b45-3b30c27af537)

**Comment by fdx-xdf** [comment]
那编译hello world有问题吗，好奇怪

**Comment by zwz12138** [comment]
> 那编译hello world有问题吗，好奇怪

hellword也寄，好像环境出了问题，我找台没装过的虚拟机重新试试，不过我确实是按知乎那个帖子来走的

**Comment by fdx-xdf** [comment]
我记得我当时环境也折腾了一下午😂，加油师傅

**Comment by zwz12138** [comment]
> 我记得我当时环境也折腾了一下午😂，加油师傅

换虚拟机了后，没毛病熬，可过360和火绒，师傅很强
![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/03269612-3763-43e8-96a3-4fd02490adfc)
![image](https://github.com/fdx-xdf/darkPulse/assets/46048020/7ea1d70c-b3c7-42e4-832e-915ac7baa0db)

**Comment by fdx-xdf** [comment]
嘿嘿，感谢师傅认可
