### ISSUE TITLE
编译太久了

### ISSUE THREAD

**Issue by JackeyLov5** [fdx-xdf/darkPulse#2]
<img width="982" alt="image" src="https://github.com/fdx-xdf/darkPulse/assets/130417202/0fd92bf8-4422-4268-9ef3-a680889dfd3c">
师傅我用cs生成的.c和bin文件都编译很久 没出结果

**Comment by JackeyLov5** [comment]
-i payload.bin -f 64 编译失败了
<img width="425" alt="image" src="https://github.com/fdx-xdf/darkPulse/assets/130417202/cedeb5cd-9984-40d7-8ee7-ec732b0c3a89">

**Comment by fdx-xdf** [comment]
编译太久的话我改一下，增加一个debug选项，默认为false就不输出中间选项了
另外师傅方便用gcc -mwindows Program.c sys_64.c aes.c -s -masm=intel -lrpcrt4测试一下我看一下具体的报错吗，下个版本增加具体的报错信息

**Comment by fdx-xdf** [comment]
师傅可以加我qq交流一下1350141940
