### ISSUE TITLE
师傅，我今天测试火绒好像不过了

### ISSUE THREAD

**Issue by answer398** [fdx-xdf/darkPulse#3]
![Uploading Snipaste_2024-05-14_17-43-01.png…]()

**Comment by answer398** [comment]
![Snipaste_2024-05-14_17-43-01](https://github.com/fdx-xdf/darkPulse/assets/119796784/28135102-862a-47ea-b7e6-ee4e17dff76d)

**Comment by fdx-xdf** [comment]
可以多尝试几个参数组合，我本地物理机还是可以过的

**Comment by jacky8lee** [comment]
组合的例子 可以给出来么
