### ISSUE TITLE
大佬报错,请指教!

### ISSUE THREAD

**Issue by daymissed** [fdx-xdf/darkPulse#4]
![image](https://github.com/fdx-xdf/darkPulse/assets/62062283/b8d78ef6-692c-409d-a43f-cb9cda3a638a)

**Comment by fdx-xdf** [comment]
第一种解决方案，你可以百度报错然后直接在program.c文件里面进行修改 ，然后如果是32位下用用gcc -mwindows -m32 Program.c sys_32.c aes.c -s -masm=intel -lrpcrt4编译，或者64位下用gcc -mwindows -m64 Program.c sys_64.c aes.c -s -masm=intel -lrpcrt4编译
第二种解决方案，你可以换一下gcc版本，我的gcc只是警告并没有报错，我的gcc版本是gcc version 8.1.0 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)

**Comment by daymissed** [comment]
感谢,我来试试

**Comment by daymissed** [comment]
更换GCC低版本正常.

**Comment by fdx-xdf** [comment]
ok
