### ISSUE TITLE
师傅 火绒还是能检测出来哈

### ISSUE THREAD

**Issue by jacky8lee** [fdx-xdf/darkPulse#5]
![111](https://github.com/fdx-xdf/darkPulse/assets/62919907/2deaa387-807e-4421-91cc-954d1ef28860)

**Comment by fdx-xdf** [comment]
![image](https://github.com/fdx-xdf/darkPulse/assets/117912115/21eecb37-5ed6-48e2-9240-30e94e39d958)
我本地物理机刚测试的，建议使用的时候改变一下参数，不要使用默认的参数

**Comment by jacky8lee** [comment]
师傅，可以把你的组合参数贴出来么

**Comment by fdx-xdf** [comment]
这个就不贴了吧，要不然你试试昨天刚更新的rust模板

**Comment by jacky8lee** [comment]
好的，谢谢
