### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by h0nayuzu** [fdx-xdf/darkPulse#8]
Failed to execute command: signal: abort trap

<img width="743" alt="image" src="https://github.com/fdx-xdf/darkPulse/assets/56476289/07fbea68-7f3c-40b2-9a10-6ebe983a597c">

**Comment by fdx-xdf** [comment]
有没有完整的报错呀

**Comment by fdx-xdf** [comment]
你看看你当前目录下有没有生成payload.bin.sgn文件

**Comment by h0nayuzu** [comment]
<img width="940" alt="image" src="https://github.com/fdx-xdf/darkPulse/assets/56476289/bcea2f1a-5e74-40d5-aa67-8c1edb05f2ea">
也没有别的输出信息

**Comment by fdx-xdf** [comment]
ok，我晚上调一下看看

**Comment by fdx-xdf** [comment]
师傅，你看一下t00ls目录下sgn有没有可执行权限

**Comment by h0nayuzu** [comment]
<img width="1388" alt="image" src="https://github.com/fdx-xdf/darkPulse/assets/56476289/d14435d3-4fd2-4b97-b0d9-bb1bb4911d86">
后面我执行了下，估计是我本机环境问题。试过重装libkeystone没效果、开摆

**Comment by fdx-xdf** [comment]
你直接用sgn对bin文件加密也报错？
